### ISSUE TITLE
KeyError 'toa'

### ISSUE THREAD

**Issue by johnvorsten** [mrpara/d2_plugy_stash_organizer#1]
I'm getting a item code data key error 'toa'.  Is there any way to add debug information so I can figure out which item is causing the KeyError? Perhaps it could print the stash position of the item?

Stack Trace - 
```python
Traceback (most recent call last):
  File "C:\Users\vorst\.spyder-py3\Scripts\d2_plugy_stash_organizer\main.py", line 301, in <module>
    main()
  File "C:\Users\vorst\.spyder-py3\Scripts\d2_plugy_stash_organizer\main.py", line 288, in main
    pages_to_ignore, item_list = parse_stash_data(stash_data, config)
  File "C:\Users\vorst\.spyder-py3\Scripts\d2_plugy_stash_organizer\main.py", line 112, in parse_stash_data
    items.append(Item(data=item))  # Initialize an Item instance for each item
  File "C:\Users\vorst\.spyder-py3\Scripts\d2_plugy_stash_organizer\item.py", line 14, in __init__
    self.group = get_item_group(self.code)     # What group does the item belong to (gloves, jewel, uber key, etc)
  File "C:\Users\vorst\.spyder-py3\Scripts\d2_plugy_stash_organizer\item_data.py", line 88, in get_item_group
    return item_data[item_code].item_group
KeyError: 'toa'
```

**Comment by mrpara** [comment]
Hey,
thanks for contacting me and letting me know about this key error. I have
fixed the issue and uploaded a new version. Please re-download the program
and try again. If you come across any other key errors, please let me know!
As for your question - yes, it would be possible, but in the case of key
errors there is no real need since they are easy to figure out by cross
referencing with online resources for item codes. Unfortunately the one I
used to generate the item codes seems to have been incomplete so there's
still a few bugs in there, and I don't want to parse another source since
there is no guarantee it will be complete as well - plus it's a lot of
semi-manual, icky work. In this case, I just looked it up here;
https://pathofdiablo.com/wiki/index.php?title=Loot_Filtration_Codes
And saw that 'toa' is token of absolution, which was missing from my item
list for some reason. I have added it and it should work now. I've already
fixed a couple of key errors and tested the tool on several stashes with
most item types in them so there shouldn't be many left. Who knows, maybe
this is the last one :)

Best of luck,
MPara

**Comment by mrpara** [comment]
Sorry, I made a blunder and added arrow twice instead of Token :facepalm:
If you've already downloaded it, please do so again...
Apologies,
 MPara
